version: '2'
services:
  db:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ivr
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  server:
    image: stikks/ivr-app
    hostname: localhost
    network_mode: host
    depends_on:
      - db
      - redis
      - elasticsearch
      - rabbit
    volumes:
      - agi-defaults:/var/lib/asterisk/sounds/defaults
      - agi-sounds:/var/lib/asterisk/sounds/files
      - freepbx-data:/var/lib/mysql
      - files-data:/opt/IVR/files
#  server:
#    image: stikks/ivr
#    hostname: server
#    ports:
#      - 8981:80
#      - 443
#      - 22
#    depends_on:
#      - db
#      - redis
#      - elasticsearch
#      - rabbit
#    volumes:
#      - ./files-data:/opt/IVR/files
  rabbit:
    image: rabbitmq
    hostname: rabbit
  redis:
    image: redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.2
    image: stikks/es
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
#  freepbx:
#    image: stikks/freepbx
#    hostname: localhost
#    network_mode: host
#    volumes:
#      - ./agi-defaults:/var/lib/asterisk/sounds/defaults
#      - ./agi-sounds:/var/lib/asterisk/sounds/files
#      - freepbx-data:/var/lib/mysql
  app:
    image: stikks/node-app
    hostname: app
    ports:
      - 4043:4043
    depends_on:
      - elasticsearch
      - rabbit
  worker:
    image: stikks/worker-app
    hostname: worker
    depends_on:
      - elasticsearch
      - rabbit
volumes:
  freepbx-data:
    external: true
  postgres-data:
      external: true
  elasticsearch-data:
      external: true
  redis-data:
      external: true
  files-data:
      external: true
  agi-sounds:
      external: true
  agi-defaults:
      external: true